# Secret Scanning Configuration
# This file configures GitHub's secret scanning to reduce false positives

# Paths to ignore during secret scanning
paths-ignore:
  # Archived and legacy code
  - 'ARCHIVE/**'
  - 'archive/**'
  
  # Test files often contain mock tokens
  - '**/test_*.py'
  - '**/*_test.py'
  - '**/tests/**'
  - '**/fixtures/**'
  
  # Demo and example files
  - '**/demo_*.py'
  - '**/*_demo.py'
  - '**/example_*.py'
  - '**/*_example.py'
  - '**/*.example'
  
  # Documentation may contain example tokens
  - 'docs/**/*.md'
  - '**/*.md'
  
  # Mock providers and test utilities
  - '**/mock_*.py'
  - '**/*_mock.py'
  - 'core/routing/providers/mock_provider.py'
  - 'enhanced_mock_provider.py'
  
  # Log files
  - '**/*.log'
  - 'logs/**'
  - 'exports/**'

# Patterns to treat as false positives
# Note: This section is for documentation - GitHub doesn't support pattern exclusion yet
# Common false positive patterns in this codebase:
# - "tokens" referring to LLM tokens, not auth tokens
# - "api_key" in configuration examples
# - JWT token references in code
# - Mock/demo authentication flows